description:
    css: '#productDescription'
    type: Text
images:
    css: '.imgTagWrapper img'
    type: Attribute
    attribute: data-a-dynamic-image
rating:
    css: '#acrPopover > span.a-declarative > a > i.a-icon.a-icon-star.a-star-4-5 > span'
    type: Text
reviews:
    css: '#acrCustomerReviewText'
    type: Text
price:
    css: 'span.a-offscreen'
    type: Text
detail:
    css: '#productFactsDesktopExpander > div.a-expander-content.a-expander-partial-collapse-content > div'
    multiple: true
    type: Text
    children:
        field:
            css: 'div > div.a-fixed-left-grid-col.a-col-left > span'
            type: Text
        value:
            css: 'div > div.a-fixed-left-grid-col.a-col-right > span'
            type: Text
        about_this_item:
            css: 'ul > li > span'
            type: Text
extra_detail:
    css: '#detailBullets_feature_div > ul > li'
    multiple: true
    type: Text
    children:
        field:
            css: 'span > span.a-text-bold'
            type: Text
        value:
            css: 'span > span:nth-child(2)'
            type: Text
variants:
    css: 'li.swatchAvailable'
    multiple: true
    type: Text
    children:
        url:
            css: 'li.swatchAvailable'
            type: Attribute
            attribute: data-dp-url
        id:
            css: 'li.swatchAvailable'
            type: Attribute
            attribute: data-defaultasin