reviews:
    css: 'div.a-section.review.aok-relative'
    multiple: true
    type: Text
    children:
        user:
            css: 'a > div.a-profile-content > span'
            type: Text
        rating:
            css: 'div:nth-child(2) > a:nth-child(1)'
            type: Text
        message:
            css: 'div.a-row.a-spacing-small.review-data'
            type: Text
next_page:
    css: '#cm_cr-pagination_bar > ul > li.a-last > a'
    type: Attribute
    attribute: href