id:
    css: '#averageCustomerReviews'
    type: Attribute
    attribute: 'data-asin'
title:
    css: '#productTitle'
    type: Text
description:
    css: '#productDescription'
    type: Text
images:
    css: '.imgTagWrapper img'
    type: Attribute
    attribute: data-a-dynamic-image
rating:
    css: '#acrPopover > span.a-declarative > a > i.a-icon.a-icon-star > span'
    type: Text
reviews_count:
    css: '#acrCustomerReviewText'
    type: Text
reviews_link:
    css: '#cr-pagination-footer-0 > a'
    type: Attribute
    attribute: href
price_range:
    css: '#corePrice_desktop > div > table'
    type: Text
variants:
    css: 'li.swatchAvailable'
    multiple: true
    type: Text
    children:
        url:
            css: 'li.swatchAvailable'
            type: Attribute
            attribute: data-dp-url
        id:
            css: 'li.swatchAvailable'
            type: Attribute
            attribute: data-defaultasin
